document.addEventListener('DOMContentLoaded', function () {
  var state = { search: '', filter: 'all', sort: 'desc', page: 1, pageSize: 10 };
  var detailsById = {};
  var tableBody = document.getElementById('inventoryTableBody');
  var paginationRow = document.getElementById('paginationRow');
  var selectedImageFile = null, imageWasRemoved = false, pendingDeleteId = null, pendingDeleteName = null;

  function escapeHtml(value) { var el = document.createElement('div'); el.textContent = value == null ? '' : String(value); return el.innerHTML; }
  function getDetails(id) { return detailsById[id] || { description: '', requirements: [] }; }
  function getStockStatus(stock) { return stock <= 0 ? {key:'out-of-stock',label:'Out of Stock'} : stock <= 3 ? {key:'low-stock',label:'Low on Stock'} : {key:'in-stock',label:'In Stock'}; }
  function formatPeso(amount) { return '₱' + Number(amount).toFixed(2); }
  function truncate(text, max) { return text.length > max ? text.slice(0, max) + '…' : text; }

  function loadDetails() {
    return fetch('../../customer/Shop%20Page/products.json').then(function (r) { if (!r.ok) throw new Error('Could not load product details.'); return r.json(); }).then(function (products) {
      detailsById = {}; products.forEach(function (product) { detailsById[product.id] = { description: product.description || '', requirements: Array.isArray(product.requirements) ? product.requirements : [] }; });
    });
  }
  function loadInventory() {
    var params = new URLSearchParams({search: state.search, filter: state.filter, sort: state.sort, page: state.page, pageSize: state.pageSize});
    tableBody.innerHTML = '<tr><td colspan="8" class="text-center">Loading inventory…</td></tr>';
    fetch('api/inventory_api/get_products.php?' + params).then(function(r){return r.json();}).then(function(result){ if(!result.success) throw new Error(result.message); renderTable(result.products); renderPagination(result.currentPage,result.totalPages); }).catch(function(){ tableBody.innerHTML = '<tr><td colspan="8" class="text-center">Could not load inventory.</td></tr>'; });
  }
  function renderTable(products) {
    if (!products.length) { tableBody.innerHTML = '<tr><td colspan="8" class="text-center">No cards match this search/filter.</td></tr>'; return; }
    tableBody.innerHTML = products.map(function(p){ var status=getStockStatus(p.stockQuantity), img=p.image||'/tcgzone/assets/images/admin/no-image.png'; return '<tr><td>'+escapeHtml(p.productId)+'</td><td><img class="table-thumb" src="'+escapeHtml(img)+'" alt=""></td><td>'+escapeHtml(p.cardName)+'</td><td>'+escapeHtml(p.category)+'</td><td>'+formatPeso(p.price)+'</td><td>'+p.stockQuantity+'</td><td><span class="stock-badge '+status.key+'">'+status.label+'</span></td><td><button class="action-edit" data-action="edit" data-id="'+p.id+'">Edit</button><span class="action-sep">|</span><button class="action-delete" data-action="delete" data-id="'+p.id+'" data-name="'+escapeHtml(p.cardName)+'">Delete</button></td></tr>'; }).join('');
  }
  function renderPagination(current,total) { if(total<=1){paginationRow.innerHTML='';return;} paginationRow.innerHTML='<button class="page-btn" data-page="'+(current-1)+'" '+(current===1?'disabled':'')+'>‹</button>'+Array.from({length:total},function(_,i){var p=i+1;return '<button class="page-btn '+(p===current?'active':'')+'" data-page="'+p+'">'+p+'</button>';}).join('')+'<button class="page-btn" data-page="'+(current+1)+'" '+(current===total?'disabled':'')+'>›</button>'; }

  var editor = document.getElementById('requirementsEditor');
  function addRequirement(item) { item=item||{label:'',value:''}; var row=document.createElement('div'); row.className='requirement-row'; row.innerHTML='<input class="form-control requirement-label" placeholder="Detail label"><textarea class="form-control requirement-value" rows="3" placeholder="Detail value"></textarea><button class="remove-requirement-btn" type="button" aria-label="Remove detail">×</button>'; row.querySelector('.requirement-label').value=item.label||''; row.querySelector('.requirement-value').value=item.value||''; row.querySelector('button').addEventListener('click',function(){row.remove();}); editor.appendChild(row); }
  function setRequirements(items) { editor.innerHTML=''; (items&&items.length?items:[{label:'',value:''}]).forEach(addRequirement); }
  function requirementsFromForm() { return Array.from(editor.querySelectorAll('.requirement-row')).map(function(row){return {label:row.querySelector('.requirement-label').value.trim(),value:row.querySelector('.requirement-value').value.trim()};}).filter(function(item){return item.label||item.value;}); }
  function openCardModal(mode, product) { document.getElementById('cardForm').reset(); selectedImageFile=null; imageWasRemoved=false; var details=product?getDetails(product.id):{description:'',requirements:[]}; document.getElementById('productId').value=product?product.id:''; document.getElementById('cardName').value=product?product.cardName:''; document.getElementById('cardCategory').value=product?product.category:'Pokémon'; document.getElementById('cardProductType').value=product?product.productType:'Cards'; document.getElementById('cardRarity').value=product?product.rarity:''; document.getElementById('cardCondition').value=product?product.condition:''; document.getElementById('cardPrice').value=product?product.price:''; document.getElementById('cardStock').value=product?product.stockQuantity:''; document.getElementById('cardDescription').value=details.description; setRequirements(details.requirements); var hasImage=product&&product.image; document.getElementById('existingImageWrap').classList.toggle('d-none',!hasImage); document.getElementById('uploadField').classList.toggle('d-none',!!hasImage); if(hasImage)document.getElementById('existingImagePreview').src=product.image; document.getElementById('cardModalBackdrop').classList.add('show'); }
  function closeModal(id){document.getElementById(id).classList.remove('show');}

  // document.getElementById('addCardBtn').addEventListener('click',function(){openCardModal('add',null);});
  document.getElementById('addRequirementBtn').addEventListener('click', function () {
    addRequirement();
  });
  document.getElementById('cardFormCancelBtn').addEventListener('click', function () {
    closeModal('cardModalBackdrop');
  });
  document.getElementById('cardImageInput').addEventListener('change',function(){var file=this.files[0];if(!file)return;if(!['image/jpeg','image/png'].includes(file.type)||file.size>1048576){alert('Use a JPG or PNG smaller than 1MB.');this.value='';return;} selectedImageFile=file; var reader=new FileReader();reader.onload=function(e){document.getElementById('existingImagePreview').src=e.target.result;document.getElementById('existingImageWrap').classList.remove('d-none');document.getElementById('uploadField').classList.add('d-none');};reader.readAsDataURL(file);});
  document.getElementById('removeImageBtn').addEventListener('click',function(){imageWasRemoved=true;selectedImageFile=null;document.getElementById('cardImageInput').value='';document.getElementById('existingImageWrap').classList.add('d-none');document.getElementById('uploadField').classList.remove('d-none');});
  tableBody.addEventListener('click',function(e){var edit=e.target.closest('[data-action="edit"]'),del=e.target.closest('[data-action="delete"]');if(edit){fetch('api/inventory_api/get_products.php?id='+encodeURIComponent(edit.dataset.id)).then(function(r){return r.json();}).then(function(result){if(result.success&&result.products.length)openCardModal('edit',result.products[0]);});}if(del){pendingDeleteId=del.dataset.id;pendingDeleteName=del.dataset.name;document.getElementById('deleteCardName').textContent=pendingDeleteName;document.getElementById('deleteModalBackdrop').classList.add('show');}});
  document.getElementById('cardForm').addEventListener('submit',function(e){e.preventDefault();var id=document.getElementById('productId').value,isEdit=!!id,fd=new FormData(),name=document.getElementById('cardName').value.trim(),category=document.getElementById('cardCategory').value,productType=document.getElementById('cardProductType').value,rarity=document.getElementById('cardRarity').value,condition=document.getElementById('cardCondition').value,price=document.getElementById('cardPrice').value,stock=document.getElementById('cardStock').value;fd.append('productId',id);fd.append('cardName',name);fd.append('category',category);fd.append('productType',productType);fd.append('rarity',rarity);fd.append('condition',condition);fd.append('price',price);fd.append('stockQuantity',stock);fd.append('imageRemoved',imageWasRemoved?'1':'0');if(selectedImageFile)fd.append('image',selectedImageFile);var btn=document.getElementById('cardFormSaveBtn');btn.disabled=true;fetch(isEdit?'api/inventory_api/update_product.php':'api/inventory_api/add_product.php',{method:'POST',body:fd}).then(function(r){return r.json();}).then(function(result){if(!result.success)throw new Error(result.message);var productId=isEdit?id:result.productId;return fetch('api/inventory_api/update_description.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({productId:productId,description:document.getElementById('cardDescription').value.trim(),requirements:requirementsFromForm(),product:{title:name,category:category,productType:productType,rarity:rarity,condition:condition,price:price,stock:stock}})});}).then(function(r){return r.json();}).then(function(result){if(!result.success)throw new Error(result.message);return loadDetails();}).then(function(){closeModal('cardModalBackdrop');loadInventory();showSuccess(isEdit?'updated':'added',name);}).catch(function(err){alert(err.message||'Could not save product.');}).finally(function(){btn.disabled=false;});});
  document.getElementById('cancelDeleteBtn').addEventListener('click',function(){closeModal('deleteModalBackdrop');}); document.getElementById('confirmDeleteBtn').addEventListener('click',function(){fetch('api/inventory_api/delete_product.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({productId:pendingDeleteId})}).then(function(r){return r.json();}).then(function(result){if(!result.success)throw new Error(result.message);closeModal('deleteModalBackdrop');loadInventory();showSuccess('deleted',pendingDeleteName);}).catch(function(err){alert(err.message||'Could not delete product.');});});
  function showSuccess(action,name){document.getElementById('successActionWord').textContent=action;document.getElementById('successCardName').textContent=name;document.getElementById('successActionSuffix').textContent=action==='deleted'?'from inventory.':'to inventory.';document.getElementById('successModalBackdrop').classList.add('show');} document.getElementById('successBackBtn').addEventListener('click',function(){closeModal('successModalBackdrop');});
  document.getElementById('cardSearchInput').addEventListener('input',function(){state.search=this.value.trim();state.page=1;loadInventory();});document.getElementById('stockFilter').addEventListener('change',function(){state.filter=this.value;state.page=1;loadInventory();});document.getElementById('productIdSort').addEventListener('change',function(){state.sort=this.value;state.page=1;loadInventory();});paginationRow.addEventListener('click',function(e){if(e.target.dataset.page){state.page=Number(e.target.dataset.page);loadInventory();}});
  loadDetails().catch(function(){detailsById={};}).finally(loadInventory);
});
